services:
  satisfactory-server:
    image: ./Dockerfile
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    ports:
      - '17777:7777/tcp'
      - '17777:7777/udp'
      - '18888:8888/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G